name: Test
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: windows-latest
    steps:
      - run: |
          # INSTALL LICENSE
          mkdir -p ~/.vaadin/
          echo '{"username":"'`echo ${{secrets.TB_LICENSE}} | cut -d / -f1`'","proKey":"'`echo ${{secrets.TB_LICENSE}} | cut -d / -f2`'"}' > ~/.vaadin/proKey
        shell: bash
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.9.0'
      - run: |
          # Show commands
          set -x
          where node.exe || true
          where node || true
          # Clean stuff
          rm -rf ~/.m2/repository/
          rm -rf ~/.vaadin/node/
          # Clone repo
          git clone https://github.com/vaadin/designer-tutorial.git
          cd designer-tutorial
          # Change version
          perl -pi -e 's|(\s*<'vaadin.version'>)[^\s]+(</'vaadin.version'>)|${1}24.7.0.alpha1${2}|g' pom.xml
          # Prepare frontend
          mvn vaadin:prepare-frontend -ntp -B || true
          ls -l ~/.vaadin/node/
          where node.exe || true
          where node || true
          ~/.vaadin/node/node -v
          ~/.vaadin/node/node.exe -v
          ~/.vaadin/node/node --version
          ~/.vaadin/node/node.exe --version
          # Build
          mvn -ntp -B || true
        shell: bash
