name: Test
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: windows-latest
    steps:
      - run: |
          # INSTALL LICENSE
          mkdir -p ~/.vaadin/
          echo '{"username":"'`echo ${{secrets.TB_LICENSE}} | cut -d / -f1`'","proKey":"'`echo ${{secrets.TB_LICENSE}} | cut -d / -f2`'"}' > ~/.vaadin/proKey
        shell: bash
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.9.0'
      - run: |
          # Show commands
          set -x
          # Clean stuff
          rm -rf ~/.m2/repository/
          rm -rf ~/.vaadin/node/
          # Clone repo
          git clone https://github.com/vaadin/designer-tutorial.git
          cd designer-tutorial
          # Change version
          perl -pi -e 's|(\s*<'vaadin.version'>)[^\s]+(</'vaadin.version'>)|${1}24.7.0.alpha1${2}|g' pom.xml
          # Run build
          mvn -ntp -B || true
          ls -l ~/.vaadin/node/
          for i in 1 2 3 4 5 6 7 8 9 0; do
            echo "Waiting $i  1 second"
            sleep 1
            ~/.vaadin/node/node -v
          done
        shell: bash
